"""
    This module defines a class FortranBinary for reading binary 
    files generated by FORTRAN unformatted I/O
"""
from .io import FortranBinary

__version__ = "1.0.9"


def main():
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("--records", action="store_true", help="List record lengths")
    parser.add_argument("filename", help="Fortran binary flie")
    args = parser.parse_args()

    if args.records:
        file_ = FortranBinary(args.filename)
        print(file_.record_byte_lengths())


if __name__ == "__main__":  # pragma: no cover
    pass
